#!/usr/bin/env bash

# rofi-ykman
# Yubikey oath utility

#2019 nukeop
#2022 Rafael Girão https://github.com/rafaelsgirao

if [ ! "$(ykman info)" ]
then
    notify-send "rofi-ykman" "Yubikey not detected." -a "rofi-ykman"
    exit 1
fi

OPTIONS=$(ykman oath accounts list)
LAUNCHER="rofi -dmenu -i -p YubikeyOATH"

option=`echo "${OPTIONS/, TOTP/\n}" | $LAUNCHER`
code=$(ykman oath accounts code "$option")
IFS=', ' read -r -a code <<< "$code"
echo "${code[-1]}" | xclip -selection clipboard
